name: master* release

on: 
  pull_request:
    branches:
      - 'master-spark*'
    types: [closed]

jobs:
  build-release:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ env.GITHUB_BASE_REF }}
        persist-credentials: false
    - name: JDK 8 Set
      uses: actions/setup-java@v1
      with: 
        java-version: 1.8
    - name: Maven Cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
        
    - name: Maven Get Version
      run: echo MVN_CURRENT_VERSION=$(mvn -B -f /home/runner/work/spark-extensions/spark-extensions/pom.xml -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec) >> $GITHUB_ENV
    - name: Set Release Version
      run: echo MVN_RELEASE_VERSION=${MVN_CURRENT_VERSION/-SNAPSHOT/} >> $GITHUB_ENV
    #- name: Printenv
    #  run: |
    #    echo "MVN_CURRENT_VERSION=${MVN_CURRENT_VERSION}
    #    echo "MVN_RELEASE_VERSION=${MVN_RELEASE_VERSION}
    #    printenv
    - name: Maven Set Release Version
      run: sed -i "/${MVN_CURRENT_VERSION}/{s//${MVN_RELEASE_VERSION}/;:p;n;bp}" pom.xml

    - name: Maven deploy to sonatype for Scala 2.11, only if on master-spark2* branch
      if: ${{ startsWith(env.GITHUB_BASE_REF, 'master-spark2') }}
      uses: samuelmeuli/action-maven-publish@v1
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
        nexus_username: ${{ secrets.SONATYPE_USERNAME }}
        nexus_password: ${{ secrets.SONATYPE_PASSWORD }}
        maven_profiles: scala-2.11,release-sonatype
        maven_args: -B -f pom.xml

    - name: Maven deploy to sonatype for Scala 2.12
      uses: samuelmeuli/action-maven-publish@v1
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
        nexus_username: ${{ secrets.SONATYPE_USERNAME }}
        nexus_password: ${{ secrets.SONATYPE_PASSWORD }}
        maven_profiles: scala-2.12,release-sonatype
        maven_args: -B -f pom.xml

    - name: Git Commit and Tag Release
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || git commit -m "Release version ${MVN_RELEASE_VERSION}" # only if there is something to committ
        git tag -f ${MVN_RELEASE_VERSION} -m "Release ${MVN_RELEASE_VERSION}"
    - name: Git Pull Master
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin ${GITHUB_BASE_REF}
    - name: Git Push Master
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ env.GITHUB_BASE_REF }}
        github_token: ${{ secrets.PAT_ACTIONS }}
        
                  
    # DEVELOP BRANCH
    - name: Develop Git Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ env.GITHUB_HEAD_REF }}
        fetch-depth: 0
        persist-credentials: false
    - name: Git Merge Master into Develop
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git fetch origin ${GITHUB_HEAD_REF}
        git checkout ${GITHUB_HEAD_REF}
        git merge origin/${GITHUB_BASE_REF}
        git diff-index --quiet HEAD || git commit -m "Release version ${MVN_RELEASE_VERSION}" # only if there is something to commit
    - name: Develop Get Next Version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.1
      with:
        current-version: ${{ env.MVN_RELEASE_VERSION }}
        version-fragment: bug
    - name: Develop Set Next Snapshot Version
      run: sed -i "/${MVN_RELEASE_VERSION}/{s//${{ steps.bump_version.outputs.next-version }}-SNAPSHOT/;:p;n;bp}" pom.xml
    - name: Develop Git Commit Snapshot
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Increment to next SNAPSHOT release" -a
    - name: Develop Git Push
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ env.GITHUB_HEAD_REF }}
        github_token: ${{ secrets.PAT_ACTIONS }}
