name: Release Build

on: 
  pull_request:
    branches:
      - 'master-spark*'
    types: [closed]

permissions:
  contents: write

jobs:
  deploy-release:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
        fetch-depth: 0
    - name: Git Config
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        server-id: central
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Maven Cache
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
        
    - name: Maven Get Version
      run: echo MVN_CURRENT_VERSION=$(mvn -B -f pom.xml -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec) >> $GITHUB_ENV
    - name: Set Release Version
      run: echo MVN_RELEASE_VERSION=${MVN_CURRENT_VERSION/-SNAPSHOT/} >> $GITHUB_ENV
    #- name: Printenv
    #  run: |
    #    printenv
    - name: Maven Set Release Version
      run: sed -i "/${MVN_CURRENT_VERSION}/{s//${MVN_RELEASE_VERSION}/;:p;n;bp}" pom.xml

    - name: Maven deploy to sonatype for Scala 2.13
      run: mvn -P release-sonatype -B -f pom.xml clean deploy
      env:
        MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    - name: Git Commit
      run: |
        git add -A
        git diff-index --quiet HEAD || git commit -m "Release version ${MVN_RELEASE_VERSION}" # only if there is something to commit
    - name: Git Pull, Tag and Push
      run: |
        git pull --rebase
        git tag -f ${MVN_RELEASE_VERSION} -m "Release ${MVN_RELEASE_VERSION}"
        git push origin ${MVN_RELEASE_VERSION} # push tag

  update-snapshot-version:
    needs: deploy-release
    if: github.event_name != 'workflow_dispatch'

    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Git Config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Maven Get Version
        run: echo MVN_CURRENT_VERSION=$(mvn -B -f pom.xml -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec) >> $GITHUB_ENV
      - name: Set Release Version
        run: echo MVN_RELEASE_VERSION=${MVN_CURRENT_VERSION/-SNAPSHOT/} >> $GITHUB_ENV

      - name: Git Merge to develop
        run: |
          git merge origin/${{ github.base_ref }} --no-commit
          git diff-index --quiet HEAD || git commit -m "Merge release version ${MVN_RELEASE_VERSION}" # only if there is something to commit

      - name: Develop Get Next Version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.1
        with:
          current-version: ${{ env.MVN_RELEASE_VERSION }}
          version-fragment: bug
      - name: Develop Set Next Snapshot version
        run: |
          mvn versions:set -B -DnewVersion=${{ steps.bump_version.outputs.next-version }}-SNAPSHOT -f pom.xml
      - name: Develop Git Commit Snapshot
        run: |
          git commit -m "Increment to next SNAPSHOT release" -a
      - name: Develop Git Push
        run: |
          git push
