name: Snapshot Build

on:
  push:
    branches:
      - 'develop-spark*'
  pull_request:
    branches:
      - 'develop-spark*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Build with Maven for Scala 2.11, only if on develop-spark2* branch
      if: ${{ contains(github.base_ref, 'develop-spark2') || contains(github.ref, 'develop-spark2') }}
      run: mvn -P scala-2.11 -B clean test --file pom.xml

    - name: Build with Maven for Scala 2.12
      run: mvn -P scala-2.12 -B clean test --file pom.xml
