name: Snapshot Build 2.12

on:
  push:
    branches: 
      - develop
      - develop-spark3
  pull_request:
    branches: 
      - develop
      - develop-spark3

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Build with Maven for Scala 2.12
      run: mvn -P scala-2.12 -B clean test --file pom.xml
